# ============================================================
# Auto-Generated Configuration Files
# Purpose: Setup files for main terraform project
# ============================================================

resource "local_file" "backend_config" {
  filename = "${var.main_project_path}/_generated.backend.tf"

  content = <<-EOT
# Auto-generated by tf-bootstrap
# This configures remote state storage in S3 with DynamoDB locking

terraform {
  backend "s3" {
    bucket       = "${aws_s3_bucket.terraform_state.id}"
    key          = "terraform.tfstate"
    region       = "${var.aws_region}"
    use_lockfile = true
    encrypt      = true
  }
}
EOT

  file_permission = "0444"
}

resource "local_file" "provider_config" {
  filename = "${var.main_project_path}/_generated.providers.tf"

  content = <<-EOT
# Auto-generated by tf-bootstrap
# AWS provider configuration with role assumption

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.28.0"
    }
  }
}

provider "aws" {
  region = "${var.aws_region}"

  assume_role {
    role_arn     = "${aws_iam_role.project_role.arn}"
    external_id  = "${var.project_name}"
    session_name = "terraform-$${terraform.workspace}"
  }

  default_tags {
    tags = {
      Project   = "${var.project_name}"
      ManagedBy = "terraform"
    }
  }
}
EOT

  file_permission = "0444"
}

resource "local_file" "variables_config" {
  count    = var.github_repo_owner != "" && var.github_repo_name != "" ? 1 : 0
  filename = "${var.main_project_path}/_generated.auto.tfvars"

  content = <<-EOT
# Auto-generated by tf-bootstrap
# Contains dynamic values from bootstrap outputs

github_actions_role_arn = "${aws_iam_role.github_actions_role[0].arn}"
EOT

  file_permission = "0444"
}

resource "local_file" "setup_info" {
  filename = "${var.main_project_path}/README-SETUP.md"

  content = <<-EOT
# Pollflow Infrastructure Setup

## Authentication

This project uses **IAM role assumption** instead of static access keys for enhanced security.

### Prerequisites

- AWS CLI configured with admin credentials
- Permissions to assume role: \`${aws_iam_role.project_role.arn}\`

### How It Works

1. **Backend (S3/DynamoDB)**: Automatically assumes the role when accessing state
2. **Provider**: Automatically assumes the role for all AWS API calls
3. **No static credentials**: No access keys stored anywhere!

### Usage

\`\`\`bash
# Verify you can assume the role
aws sts assume-role \\
  --role-arn ${aws_iam_role.project_role.arn} \\
  --role-session-name terraform-test \\
  --external-id ${var.project_name}

# If successful, proceed with terraform
terraform init
terraform plan
terraform apply
\`\`\`

### Role Details

- **Role ARN**: \`${aws_iam_role.project_role.arn}\`
- **Role Name**: \`${aws_iam_role.project_role.name}\`
- **External ID**: \`${var.project_name}\` (for additional security)
- **Session Name**: \`terraform-<workspace>\`

### Troubleshooting

**Error: "AccessDenied"**
- Ensure your current AWS credentials have \`sts:AssumeRole\` permission
- Verify the external ID matches: \`${var.project_name}\`

**Error: "InvalidClientTokenId"**
- Check your AWS CLI configuration: \`aws sts get-caller-identity\`
- Ensure you're using admin credentials that created the bootstrap

## Security Benefits

✅ No static access keys
✅ No secrets in state files  
✅ Temporary credentials (auto-rotate every 12 hours)
✅ CloudTrail logs show both your identity AND the assumed role
✅ Can revoke access instantly by modifying role trust policy
EOT

  file_permission = "0444"
}
