apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-broker
  labels:
    app: poll-broker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: poll-broker
  template:
    metadata:
      labels:
        app: poll-broker
    spec:
      containers:
        - name: poll-broker
          image: 058264398399.dkr.ecr.eu-west-3.amazonaws.com/pollflow-poll-broker:latest
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: dbname
            - name: REDIS_HOST
              value: "redis-primary"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
