apiVersion: v1
kind: Service
metadata:
  name: poll-broker
  labels:
    app: poll-broker
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: poll-broker
