# Auto-generated by tf-bootstrap
# This configures remote state storage in S3 with DynamoDB locking

terraform {
  backend "s3" {
    bucket       = "pollflow-terraform-state-058264398399"
    key          = "terraform.tfstate"
    region       = "eu-west-3"
    use_lockfile = true
    encrypt      = true
  }
}
