apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 058264398399.dkr.ecr.eu-west-3.amazonaws.com/pollflow-worker:latest
          env:
            - name: REDIS_HOST
              value: "redis-primary"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: dbname
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
