# Auto-generated by tf-bootstrap
# AWS provider configuration with role assumption

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "eu-west-3"

  assume_role {
    role_arn     = "arn:aws:iam::058264398399:role/projects/cloudpollpro-bootstrap-terraform-role"
    external_id  = "cloudpollpro-bootstrap"
    session_name = "terraform-${terraform.workspace}"
  }

  default_tags {
    tags = {
      Project   = "cloudpollpro-bootstrap"
      ManagedBy = "terraform"
    }
  }
}
